#!/usr/bin/env bash

set -euo pipefail

device=${BOOTSTRAP_LUKS_DEVICE}
key_file=${BOOTSTRAP_LUKS_INITRD_KEY_FILE}

cryptsetup luksChangeKey "$device" --key-slot 0

umask a=

temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT
dd bs=512 count=4 if=/dev/random of="$temp_file" iflag=fullblock

cryptsetup luksChangeKey "$device" --key-slot 1 --key-file "$key_file" "$temp_file"

mv -f "$temp_file" "$key_file"

mkinitcpio --allpresets
