#!/usr/bin/env bash

set -eu

rm -f /etc/machine-id

echo "$INSTALL_HOSTNAME" >/etc/hostname

echo "LANG=$INSTALL_LANG" >/etc/locale.conf
sed -i -e "/#$INSTALL_LANG/s/^#//" /etc/locale.gen
locale-gen

cat >/etc/vconsole.conf <<-EOF
FONT=$INSTALL_FONT
KEYMAP=$INSTALL_KEYMAP
EOF

ln -sf /usr/share/zoneinfo/"$INSTALL_TIMEZONE" /etc/localtime
hwclock --systohc --utc

echo "%$INSTALL_SUDOER_GROUP ALL=(ALL) ${INSTALL_SUDOER_NOPASSWD:+NOPASSWD:}ALL" >/etc/sudoers.d/"$INSTALL_SUDOER_GROUP"

useradd \
    --create-home --groups users,"$INSTALL_SUDOER_GROUP" \
    ${INSTALL_SUDOER_SHELL:+--shell "$INSTALL_SUDOER_SHELL"} \
    "$INSTALL_SUDOER_USERNAME"

chpasswd <<<"$INSTALL_SUDOER_USERNAME:$INSTALL_SUDOER_PASSWORD"

passwd --delete root

if ((INSTALL_DEVICE_IS_SSD)); then
    systemctl enable fstrim.timer
fi

if ((INSTALL_NET_HAS_WIRELESS)); then
    systemctl enable iwd.service
fi

systemctl enable systemd-{networkd,resolved,timesyncd}.service
systemctl enable reflector.{service,timer}
systemctl enable sshd.service
