#!/usr/bin/env bash

set -eu

packages=(
    base
    btrfs-progs
    linux
    linux-firmware
    lvm2
    mkinitcpio
    openssh
    reflector
    sudo
)

case $INSTALL_BOOT_TYPE in
uefi) packages+=(grub efibootmgr) ;;
bios) packages+=(grub-bios) ;;
esac

if ((INSTALL_NET_HAS_WIRELESS)); then
    packages+=(iwd)
fi

if [[ -v INSTALL_CPU_VENDOR ]]; then
    packages+=("$INSTALL_CPU_VENDOR"-ucode)
fi

if [[ -v INSTALL_SUDOER_SHELL ]]; then
    packages+=("${INSTALL_SUDOER_SHELL##*/}")
fi

printf "%s\n" "${packages[@]}"
