#!/usr/bin/env bash

set -eu

echo "LANG=$INSTALL_LANG" >/etc/locale.conf
sed -i -e "/#$INSTALL_LANG/s/^#//" /etc/locale.gen
locale-gen

cat >/etc/vconsole.conf <<-EOF
FONT=$INSTALL_FONT
KEYMAP=$INSTALL_KEYMAP
EOF

echo "$INSTALL_HOSTNAME" >/etc/hostname

ln -sf "/usr/share/zoneinfo/$INSTALL_TIMEZONE" /etc/localtime
hwclock --systohc --utc

echo "%wheel ALL=(ALL) ${INSTALL_SUDO_NOPASSWD:+NOPASSWD:}ALL" >/etc/sudoers.d/wheel

useradd \
    --create-home --groups users,wheel \
    ${INSTALL_SUDOER_SHELL:+--shell "$INSTALL_SUDOER_SHELL"} \
    "$INSTALL_SUDOER_USERNAME"

chpasswd <<<"$INSTALL_SUDOER_USERNAME:$INSTALL_SUDOER_PASSWORD"

passwd --delete root

systemctl enable paccache.timer

systemctl enable systemd-{networkd,resolved,timesyncd}.service

systemctl enable {sshd,iwd}.service

systemctl enable reflector.{service,timer}

systemctl enable fstrim.timer

if [[ $INSTALL_VM_TYPE == oracle ]]; then
    systemctl enable vboxservice.service
    gpasswd --add "$INSTALL_SUDOER_USERNAME" vboxsf
fi
