#!/usr/bin/env bash

set -eu

backup_dir=$PWD/backups/$HOSTNAME

from_paths=(
    /home
    /var/lib/iwd
    /var/cache/pacman/pkg
)

for from_path in "${from_paths[@]}" "$@"; do
    if [[ -d $from_path ]]; then
        to_path=$backup_dir/${from_path#/}
        mkdir -p "$to_path"
        sudo rsync -var --delete "$from_path"/ "$to_path"
    fi
done
