#!/usr/bin/env bash

set -euo pipefail

close-root

if [[ $BOOTSTRAP_BOOT_FIRMWARE == uefi ]]; then
    close-uefi
fi

if [[ -v BOOTSTRAP_USE_SWAP ]]; then
    close-swap
    close-lvm-swap
fi

close-lvm-root
close-lvm

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    close-luks
fi
