#!/usr/bin/env bash

set -euo pipefail

boot-config
initrd-config

if [[ -v BOOTSTRAP_USE_TRIM ]]; then
    trim-config
fi

network-config

if [[ -v BOOTSTRAP_USE_WIRELESS ]]; then
    wireless-config
fi

hostname-config
timezone-config
lang-config
keymap-config
mirrors-config
admin-config
