#!/usr/bin/env bash

set -euo pipefail

partition

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    luks-format
    luks-open
fi

lvm-create

if [[ -v BOOTSTRAP_USE_SWAP ]]; then
    swap-create
    swap-open
fi

fs-format
fs-mount

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    luks-addkey
fi
