#!/usr/bin/env bash

set -euo pipefail

partition

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    luks-format
    luks-open
fi

lvm-create

swap-create
swap-open

fs-format
fs-mount

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    luks-addkey
fi
