#!/usr/bin/env bash

set -euo pipefail

templates_dir=$PWD/config/templates

while IFS= read -r template_file; do
    system_file=/${template_file#"$templates_dir"/}
    if [[ -f $system_file ]]; then
        diff --recursive --no-dereference --unified --color \
            "$system_file" "$template_file"
    fi
done < <(find "$templates_dir" -type f)
