#!/usr/bin/env bash

set -eu

host=${1:?Missing hostname}
host_dir=$PWD/hosts/$host

hostnamectl set-hostname "$host"

iwd_dir=$host_dir/var/lib/iwd
if [[ -d $iwd_dir ]]; then
    cp -a "$iwd_dir"/*.psk "${iwd_dir#"$host_dir"}"
    systemctl restart iwd.service
fi

./scripts/init
