#!/usr/bin/env bash

set -eu

mkdir -p ~/.ssh
chmod 700 ~/.ssh
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
curl -sL https://gitlab.com/jmcantrell.keys >>~/.ssh/authorized_keys

sed -i "/^DHCP=/a MulticastDNS=yes" /etc/systemd/network/*.network
systemctl restart systemd-networkd.service
/usr/lib/systemd/systemd-networkd-wait-online

# Only download a copy of the repository if this script doesn't exist locally.
if [[ ${0##*/} != init ]]; then
    curl -sL -o ~/bootstrap.tar.gz \
        https://gitlab.com/jmcantrell/bootstrap-arch/-/archive/main/bootstrap-arch-main.tar.gz
fi
