#!/usr/bin/env bash

set -eu

mkdir -p ~/.ssh
chmod 700 ~/.ssh
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
curl -sL https://github.com/jmcantrell.keys >>~/.ssh/authorized_keys

sed -i "/^DHCP=/a MulticastDNS=yes" /etc/systemd/network/*.network
systemctl restart systemd-networkd.service
/usr/lib/systemd/systemd-networkd-wait-online

# Only download a copy of the repository if this script doesn't exist locally.
if [[ ${0##*/} != init ]]; then
    /usr/lib/systemd/systemd-networkd-wait-online
    curl -sSL --progress-bar -o ~/bootstrap.zip \
        https://github.com/jmcantrell/bootstrap-arch/archive/refs/heads/main.zip
fi
