#!/usr/bin/env bash

set -euo pipefail

touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
curl -sSL https://meta.sr.ht/~jmcantrell.keys >>~/.ssh/authorized_keys

# It's assumed that if this script is named (i.e. it's not being piped), it
# exists already locally and, presumably, with the rest of the repository.
# Otherwise, download an archive of the repository somewhere.
if [[ ${0##*/} != inject ]]; then
    mkdir -p /tmp/bootstrap
    curl -sSL https://git.sr.ht/~jmcantrell/arch-bootstrap/archive/main.tar.gz |
        tar -xzf -C /tmp/bootstrap --strip-components=1 -
fi
