#!/usr/bin/env bash

set -euo pipefail

mkdir -p ~/.ssh
chmod 700 ~/.ssh
touch ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
curl -sL https://github.com/jmcantrell.keys >>~/.ssh/authorized_keys

sed -i '/^\[Network\]/a MulticastDNS=yes' /etc/systemd/network/*.network
systemctl restart systemd-networkd.{service,socket}
/usr/lib/systemd/systemd-networkd-wait-online

# Only download a copy of the repository if this script doesn't exist locally.
# If this script is being piped to bash, or run via the script boot parameter,
# the script name will be something other than `inject`.
if [[ ${0##*/} != inject ]]; then
    git clone https://github.com/jmcantrell/bootstrap-arch.git bootstrap
fi
