#!/usr/bin/env bash

set -euo pipefail

curl -fsSL https://meta.sr.ht/~jmcantrell.keys |
    install -D -m600 /dev/stdin ~/.ssh/authorized_keys

sed -i '/^\[Network\]$/a MulticastDNS=yes' /etc/systemd/network/*.network
networkctl reload

# It's assumed that if this script is named (i.e. it's not being piped), it
# exists already locally and, presumably, with the rest of the repository.
# Otherwise, download an archive of the repository somewhere.
if [[ ${0##*/} != inject ]]; then
    mkdir -p /tmp/bootstrap
    curl -fsSL https://git.sr.ht/~jmcantrell/arch-bootstrap/archive/main.tar.gz |
        tar -xzf - -C /tmp/bootstrap --strip-components=1
fi
