#!/usr/bin/env bash

set -euo pipefail

create-partitions

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    create-luks
    open-luks
fi

create-lvm

if [[ -v BOOTSTRAP_USE_SWAP ]]; then
    create-swap
    open-swap
fi

create-fs
open-fs

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    create-luks-keyfile
fi

install-packages

if [[ -v BOOTSTRAP_USE_TRIM ]]; then
    config-trim
fi

config-network

if [[ -v BOOTSTRAP_USE_WIRELESS ]]; then
    config-wireless
fi

config-hostname
config-timezone
config-ntp
config-lang
config-keymap
config-mirrors
config-admin
config-ssh
config-boot
config-initrd

install-locale
install-fstab
install-initrd
install-boot
