#!/usr/bin/env bash

set -eu

localize

partition

if ((INSTALL_DEVICE_IS_LUKS)); then
    luks-format
    luks-open
fi

lvm-create

swap-create
swap-open

fs-format
fs-mount

if ((INSTALL_DEVICE_IS_LUKS)); then
    luks-addkey
fi

packages-install
chroot-install
fstab-install
initrd-install
boot-install

# The rest is not normally necessary, but illustrates the procedure for cleanly
# unmounting the new installation.

# fs-umount
# swap-close
# lvm-close

# if ((INSTALL_DEVICE_IS_LUKS)); then
#     luks-close
# fi
