#!/usr/bin/env bash

set -eu

localize

partition

if ((INSTALL_DEVICE_IS_LUKS)); then
    luks-format
    luks-open
fi

lvm-create

swap-create
swap-open

fs-format
fs-mount

if ((INSTALL_DEVICE_IS_LUKS)); then
    luks-addkey
fi

packages-install
chroot-install
fstab-install
initrd-install
boot-install
