#!/usr/bin/env bash

set -euo pipefail

if [[ -v BOOTSTRAP_KEYMAP ]]; then
    loadkeys "$BOOTSTRAP_KEYMAP"
fi

if [[ -v BOOTSTRAP_FONT ]]; then
    setfont "$BOOTSTRAP_FONT"
fi

# Update the pacman mirrorlist, if possible.
if timeout 1 ping -q -c1 archlinux.org &>/dev/null; then
    reflector \
        --save /etc/pacman.d/mirrorlist \
        --protocol https --latest 5 --sort age \
        --country "$BOOTSTRAP_MIRROR_COUNTRY"
else
    # If there's no network access, stop trying to update the mirror list.
    systemctl stop reflector.service
fi
