#!/usr/bin/env bash

set -euo pipefail

if [[ -v BOOTSTRAP_KEYMAP ]]; then
    loadkeys "$BOOTSTRAP_KEYMAP"
fi

if [[ -v BOOTSTRAP_FONT ]]; then
    setfont "$BOOTSTRAP_FONT"
fi

systemctl stop reflector.service

# Update the pacman mirrorlist, if possible.
if timeout 1 ping -q -c1 archlinux.org &>/dev/null; then
    reflector --verbose \
        --save /etc/pacman.d/mirrorlist \
        --protocol https --latest 5 --sort age \
        --country "$BOOTSTRAP_MIRROR_COUNTRY"
fi
