#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

self_name=${0##*/}

usage="Create a cloud-init iso file.

Usage:
    $self_name [OPTIONS] FILE

Options:
    -h    show this help message and exit

    -e    edit files before building

    -s    include the user's ssh public keys
    -k    include the system's iwd pre-shared keys

    -m MOUNT      add MOUNT line to fstab
                  (where MOUNT is like 'SOURCE TARGET[ TYPE[ OPTIONS[ DUMP[ PASS]]]]')

    -f MAPPING    add file MAPPING to the live system
                  (where MAPPING is like 'PATH[@PERMISSIONS]=FILE')

    -r COMMAND    add COMMAND to be run after boot

Arguments:
    FILE    write cloud-init iso to FILE
"

users=()
mounts=()
write_files=()
runcmd=()

write_files+=("$(jo -- path=/etc/systemd/system/reflector.service -s permissions=0000)")

runcmd+=("systemctl stop reflector.service && rm /etc/systemd/system/reflector.service && systemctl daemon-reload")
runcmd+=("sed -i '/^\[Network\]/a MulticastDNS=yes' /etc/systemd/network/*.network && networkctl reload")

edit=0
include_ssh=0
include_keys=0
declare -A mount_lines=()

for name in bootstrap{,_repo}; do
    mount_lines["/mnt/$name"]="LABEL=${name@U} /mnt/$name auto defaults,nofail 0 2"
done

while getopts "eskm:f:r:h" opt; do
    case $opt in
        e) edit=1 ;;
        s) include_ssh=1 ;;
        k) include_keys=1 ;;
        m)
            read -r _ target _ <<<"$OPTARG"
            mount_lines[$target]=$OPTARG
            ;;
        f)
            path=${OPTARG%%=*}
            file=${OPTARG##*=}
            if [[ $path == *@* ]]; then
                permissions=${path##*@}
                path=${path%%@*}
            else
                permissions=$(stat -L -c %a -- "$file")
            fi
            write_files+=("$(jo -- encoding=b64 path="$path" -s permissions="$permissions" content=%"$file")")
            ;;
        r) runcmd+=("$OPTARG") ;;
        h)
            printf "%s\n" "$usage"
            exit
            ;;
        *) exit 2 ;;
    esac
done
shift $((OPTIND - 1))

iso_file=${1:?missing iso file}

temp_dir=$(mktemp -td -- "$self_name.$$".XXXXXXXXXX)
trap 'rm -rf -- "$temp_dir"' EXIT

for line in "${mount_lines[@]}"; do
    read -ra tokens <<<"$line"
    args=()
    for token in "${tokens[@]}"; do
        args+=(-s "$token")
    done
    mounts+=("$(jo -a -- "${args[@]}")")
done

if ((include_ssh)); then
    declare -A ssh_pubkeys=()

    if reply=$(ssh-add -L); then
        while IFS= read -r pubkey; do
            ssh_pubkeys[$pubkey]=1
        done <<<"$reply"
    fi

    if [[ -f ~/.ssh/authorized_keys ]]; then
        while IFS= read -r pubkey; do
            ssh_pubkeys[$pubkey]=1
        done <~/.ssh/authorized_keys
    fi

    for pubkey_file in ~/.ssh/*.pub; do
        privkey_file=${pubkey_file%.*}
        if [[ -f $pubkey_file && -f $privkey_file ]] && ssh-keygen -y -f "$privkey_file" | cmp -s -- "$pubkey_file" -; then
            ssh_pubkeys[$(<"$pubkey_file")]=1
        fi
    done

    users+=("$(jo name=root ssh_authorized_keys="$(jo -a "${!ssh_pubkeys[@]}")")")
fi

should_restart_iwd=0

if ((include_keys)); then
    while IFS= read -r -d '' psk_file; do
        should_restart_iwd=1
        write_files+=("$(sudo jo encoding=b64 path="$psk_file" content=%"$psk_file")")
    done < <(sudo find /var/lib/iwd -type f -name "*.psk" -print0)
fi

if ((should_restart_iwd)); then
    runcmd+=("systemctl restart iwd.service")
fi

env_file=$temp_dir/env

set | awk '/^BOOTSTRAP_/ { print "export " $0 }' >"$env_file"
printf "\n# vi:ft=bash\n" >>"$env_file"

write_files+=("$(jo -- encoding=b64 path=/root/bootstrap.env -s permissions='0600' content=%"$env_file")")

script_file=$temp_dir/script

cat >"$script_file" <<EOF
#!/usr/bin/env bash

set -euo pipefail

exec > >(tee /root/bootstrap.log) 2>&1

source /root/bootstrap.env

cd /mnt/bootstrap
source ./init
print-config
if [[ ! -v BOOTSTRAP_PACKAGE_REPO_SERVER ]]; then
    refresh-mirrors
fi
create-target
install-target

cd /root
if [[ -f ./bootstrap.local && -x ./bootstrap.local ]]; then
    ./bootstrap.local
fi

cd "\$BOOTSTRAP_TARGET_MOUNT_DIR"
mkdir -p ./usr/local/etc
cp -t ./usr/local/etc /root/bootstrap.env
mkdir -p ./usr/local/var/log
cp -t ./usr/local/var/log /root/bootstrap.log

if [[ \$BOOTSTRAP_FS_ROOT_KIND == btrfs && -v BOOTSTRAP_FS_ROOT_ENABLE_SUBVOLUMES ]]; then
    chroot-target mkdir -p /.snapshots/@
    chroot-target btrfs subvolume snapshot -r / /.snapshots/@/bootstrap
fi
EOF

write_files+=("$(jo -- encoding=b64 path=/root/bootstrap -s permissions='0755' content=%"$script_file")")

user_data=()

if ((${#users[@]} > 0)); then
    user_data+=(users="$(jo -a -- "${users[@]}")")
fi

if ((${#mounts[@]} > 0)); then
    user_data+=(mounts="$(jo -a -- "${mounts[@]}")")
fi

if ((${#write_files[@]} > 0)); then
    user_data+=(write_files="$(jo -a -- "${write_files[@]}")")
fi

if ((${#runcmd[@]} > 0)); then
    user_data+=(runcmd="$(jo -a -- "${runcmd[@]}")")
fi

umask 077

cidata_dir=$temp_dir/cidata
mkdir -p -- "$cidata_dir"

cat >"$cidata_dir"/meta-data <<EOF
${BOOTSTRAP_HOSTNAME:+local-hostname: $BOOTSTRAP_HOSTNAME}
EOF

cat >"$cidata_dir"/user-data <<EOF
#cloud-config
$(jo -- "${user_data[@]}" | yq -p json)
EOF

if ((edit)); then
    $EDITOR -- "$env_file" "$script_file" "$cidata_dir"/{user,meta}-data
fi

mkdir -p -- "$(dirname -- "$iso_file")"
xorriso -as genisoimage -output "$iso_file" -volid CIDATA -joliet -rock "$cidata_dir"/*
