#!/usr/bin/env bash

set -euo pipefail

self_name=${0##*/}

repo_name=bootstrap
repo_dir=/var/lib/$repo_name/repo

usage="Create/update a custom repository for bootstrapping.

Usage:
    $self_name -h|--help
    $self_name [PACKAGE...]

Arguments:
    PACKAGE    also install PACKAGE

This will create a pacman repository named ${repo_name@Q} at the following path:

    $repo_dir

This repository will contain all packages needed to bootstrap an Arch Linux system.
"

if (($# > 0)); then
    if [[ $1 == -h || $1 == --help ]]; then
        printf "%s\n" "$usage"
        exit
    fi
fi

((EUID == 0)) || exec sudo "$0" "$@"

temp_dir=/tmp/${repo_name}-db
trap 'rm -rf "$temp_dir"' EXIT
mkdir -p "$temp_dir" 

# Remove any broken symlinks.
find "$repo_dir" -xtype l -delete

find ./config/packages -type f -exec cat {} + | sort -u |
    pacman -Syuw --noconfirm --needed --dbpath="$temp_dir" --cachedir="$repo_dir" -

# Only keep the latest packages.
paccache --verbose --remove --keep 1 --cachedir "$repo_dir"

repo-add --new --remove --include-sigs \
    "$repo_dir/$repo_name".db.tar.zst \
    "$repo_dir"/*.pkg.tar.zst

# Deduplicate downloaded packages that are cached.
for src_file in /var/cache/pacman/pkg/*.pkg.tar.zst{,.sig}; do
    dst_file=$repo_dir/${src_file##*/}
    if [[ -f $dst_file && ! -L $dst_file ]]; then
        rm -f "$dst_file"
        ln -vsn "$src_file" "$dst_file"
    fi
done
