#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

self_name=${0##*/}

default_repo_dir=/var/lib/bootstrap/repo

usage="Create a custom repository for bootstrapping.

Usage:
    $self_name -h|--help
    $self_name [DIRECTORY]

Arguments:
    DIRECTORY    create repository in DIRECTORY
                 (default: ${default_repo_dir@Q})
"

if (($# > 0)); then
    if [[ $1 == -h || $1 == --help ]]; then
        printf "%s\n" "$usage"
        exit
    fi
fi

((EUID == 0)) || exec sudo "$0" "$@"

repo_dir=${1:-$default_repo_dir}

temp_dir=/tmp/bootstrap-db
trap 'rm -rf "$temp_dir"' EXIT
mkdir -p "$temp_dir"

mkdir -p "$repo_dir"
find ./config/packages -type f -exec cat {} + | sort -u |
    pacman -Syuw --noconfirm --needed --dbpath="$temp_dir" --cachedir="$repo_dir" -

paccache --verbose --remove --keep 1 --cachedir "$repo_dir"

repo-add --new --remove --include-sigs "$repo_dir"/bootstrap.db.tar.zst "$repo_dir"/*.pkg.tar.zst
