#!/usr/bin/env bash

set -euo pipefail

self_name=${0##*/}

packages_dir=/var/cache/bootstrap/repo

disk_size=20G

usage="Bootstrap a virtual machine.

Usage:
    $self_name -h|--help
    $self_name [OPTIONS] ISO_FILE DISK_FILE

Options:
    -m SIZE    specify memory size (default: same as ./scripts/vm)
    -d SIZE    specify disk size (default: $disk_size)

    -e    edit configuration before building cloud-init image
    -y    proceed with the installation and reboot into system

Arguments:
    ISO_FILE     installation media ISO file
    DISK_FILE    data disk image file
"

if (($# > 0)); then
    if [[ $1 == -h || $1 == --help ]]; then
        printf "%s\n" "$usage"
        exit
    fi
fi

temp_dir=$(mktemp -d -t "$self_name-$$".XXXXXXXXXX)
trap 'rm -rf "$temp_dir"' EXIT

ci_opts=()
vm_opts=()
disk_file=$temp_dir/disk.cow
cidata_file=$temp_dir/cidata.iso

while getopts "m:d:ey" opt; do
    case $opt in
    m) vm_opts+=(-"$opt") ;;
    e | y) ci_opts+=(-"$opt") ;;
    d) disk_size=$OPTARG ;;
    *) exit 2 ;;
    esac
done
shift $((OPTIND - 1))

media_file=${1:?missing media file}
disk_file=${2:?missing disk file}

if [[ -f $disk_file ]]; then
    printf "%s: disk file already exists: %q\n" "$0" "$disk_file" >&2
    exit 2
fi

printf "creating virtual machine disk: %q (%s)\n" "$disk_file" "$disk_size"
qemu-img create -f qcow2 "$disk_file" -o nocow=on "$disk_size"

export BOOTSTRAP_TARGET_DEVICE=/dev/sda
export BOOTSTRAP_PACKAGE_REPO_DIR=/mnt/packages
export BOOTSTRAP_USE_TRIM=1

./scripts/mkci "${ci_opts[@]}" \
    -m "bootstrap /mnt/bootstrap 9p trans=virtio,version=9p2000.L 0 0" \
    -m "packages /mnt/packages 9p trans=virtio,version=9p2000.L 0 0" \
    "$cidata_file"

./scripts/vm "${vm_opts[@]}" \
    -i "$media_file" \
    -i "$cidata_file" \
    -s bootstrap="$PWD" \
    -s packages="$packages_dir" \
    "$disk_file"
