#!/usr/bin/env bash

set -euo pipefail

self_name=${0##*/}

repo_dir=/var/cache/bootstrap/repo

usage="Create a virtual machine.

Usage:
    $self_name -h|--help
    $self_name [OPTIONS] ISO_FILE DISK_FILE

Options:
    -i FILE    store cloud-init ISO in FILE (default: ephemeral)

    -m SIZE    specify memory size (default: same as ./scripts/vm)

    -p PORT    forward host PORT to guest port 22
               (tcp only, default: same as ./scripts/vm)

    -c ID    set guest vsock client ID
             (default: same as ./scripts/vm)

    -e    edit configuration before booting the live system

Arguments:
    ISO_FILE     installation media ISO file
    DISK_FILE    data disk image file
"

if (($# > 0)); then
    if [[ $1 == -h || $1 == --help ]]; then
        printf "%s\n" "$usage"
        exit
    fi
fi

temp_dir=$(mktemp -d -t "$self_name-$$".XXXXXXXXXX)
trap 'rm -rf "$temp_dir"' EXIT

ci_opts=()
vm_opts=()
disk_file=$temp_dir/disk.cow
cidata_file=$temp_dir/cidata.iso

while getopts "i:m:p:c:e" opt; do
    case $opt in
    i) cidata_file=$OPTARG ;;
    m) vm_opts+=(-"$opt") ;;
    p | c) vm_opts+=(-"$opt" "$OPTARG") ;;
    e) ci_opts+=(-"$opt") ;;
    *) exit 2 ;;
    esac
done
shift $((OPTIND - 1))

media_file=${1:?missing media file}
disk_file=${2:?missing disk file}

export BOOTSTRAP_TARGET_DEVICE=/dev/sda
export BOOTSTRAP_PACKAGE_REPO_DIR=/mnt/packages
export BOOTSTRAP_ENABLE_TRIM=1

./scripts/mkci "${ci_opts[@]}" \
    -m "bootstrap /mnt/bootstrap 9p trans=virtio,version=9p2000.L 0 0" \
    -m "packages /mnt/packages 9p trans=virtio,version=9p2000.L 0 0" \
    "$cidata_file"

./scripts/vm "${vm_opts[@]}" \
    -i "$media_file" \
    -i "$cidata_file" \
    -s bootstrap="$PWD" \
    -s packages="$repo_dir" \
    "$disk_file"
