#!/usr/bin/env bash

export BOOTSTRAP_ROOT_DIR=$PWD

export PATH=$BOOTSTRAP_ROOT_DIR/bin:$PATH

export BOOTSTRAP_LIB_DIR=$BOOTSTRAP_ROOT_DIR/lib
export BOOTSTRAP_CONFIG_DIR=$BOOTSTRAP_ROOT_DIR/config

: "${BOOTSTRAP_INSTALL_DEVICE:?missing install device}"

for file in "$BOOTSTRAP_LIB_DIR"/prepare/*.bash; do
    if ! . "$file"; then
        printf "unable to source file: %q\n" "$file" >&2
        return 1
    fi
done
unset file
