#!/usr/bin/env bash

export BOOTSTRAP_ROOT=$PWD

export BOOTSTRAP_CONFIG=${1:-${BOOTSTRAP_CONFIG:-$BOOTSTRAP_ROOT/config}}

export PATH=$BOOTSTRAP_ROOT/bin:$PATH

export BOOTSTRAP_MOUNT=${BOOTSTRAP_MOUNT:-/mnt/install}

env_file=$BOOTSTRAP_CONFIG/env
if [[ -f $env_file ]] && ! . "$env_file"; then
    printf "unable to source file: %q\n" "$env_file" >&2
    return 1
fi

unset part_prefix
if [[ ${BOOTSTRAP_DEVICE##*/} == nvme* ]]; then
    part_prefix=p
fi

export BOOTSTRAP_BOOT_DEVICE=${BOOTSTRAP_BOOT_DEVICE:-${BOOTSTRAP_DEVICE}${part_prefix:-}1}
export BOOTSTRAP_SYS_DEVICE=${BOOTSTRAP_SYS_DEVICE:-${BOOTSTRAP_DEVICE}${part_prefix:-}2}

if [[ -v BOOTSTRAP_USE_LUKS ]]; then
    export BOOTSTRAP_LUKS_DEVICE=$BOOTSTRAP_SYS_DEVICE
    export BOOTSTRAP_LUKS_MAPPER_NAME=${BOOTSTRAP_LUKS_MAPPER_NAME:-sys}
    export BOOTSTRAP_LUKS_MAPPER=/dev/mapper/$BOOTSTRAP_LUKS_MAPPER_NAME
    export BOOTSTRAP_LUKS_KEYFILE=${BOOTSTRAP_LUKS_KEYFILE:-/crypto_keyfile.bin}
    export BOOTSTRAP_LUKS_PASSPHRASE=${BOOTSTRAP_LUKS_PASSPHRASE:-hunter2}
    export BOOTSTRAP_LVM_DEVICE=$BOOTSTRAP_LUKS_MAPPER
else
    export BOOTSTRAP_LVM_DEVICE=$BOOTSTRAP_SYS_DEVICE
fi

export BOOTSTRAP_LVM_VG_NAME=${BOOTSTRAP_LVM_VG_NAME:-sys}

export BOOTSTRAP_LVM_LV_SWAP_NAME=${BOOTSTRAP_LVM_LV_SWAP_NAME:-swap}

if [[ ! -v BOOTSTRAP_LVM_LV_SWAP_SIZE ]]; then
    if [[ -v BOOTSTRAP_MEMORY_SIZE ]]; then
        BOOTSTRAP_LVM_LV_SWAP_SIZE=$BOOTSTRAP_MEMORY_SIZE
    elif memory_size=$(memory-size); then
        BOOTSTRAP_LVM_LV_SWAP_SIZE=$memory_size
    else
        printf "unable to get information about physical memory\n" >&2
        return 1
    fi
    export BOOTSTRAP_LVM_LV_SWAP_SIZE
fi

export BOOTSTRAP_LVM_LV_ROOT_NAME=${BOOTSTRAP_LVM_LV_ROOT_NAME:-root}
export BOOTSTRAP_LVM_LV_ROOT_EXTENTS=${BOOTSTRAP_LVM_LV_ROOT_EXTENTS:-+100%FREE}

export BOOTSTRAP_ROOT_DEVICE=/dev/mapper/$BOOTSTRAP_LVM_VG_NAME-$BOOTSTRAP_LVM_LV_ROOT_NAME
export BOOTSTRAP_SWAP_DEVICE=/dev/mapper/$BOOTSTRAP_LVM_VG_NAME-$BOOTSTRAP_LVM_LV_SWAP_NAME

export BOOTSTRAP_FS_SWAP_LABEL=${BOOTSTRAP_FS_SWAP_LABEL:-swap}
export BOOTSTRAP_FS_ROOT_LABEL=${BOOTSTRAP_FS_ROOT_LABEL:-root}
export BOOTSTRAP_FS_ROOT_OPTIONS=${BOOTSTRAP_FS_ROOT_OPTIONS:-autodefrag,compress=zstd}

if [[ ! -v BOOTSTRAP_CPU_VENDOR ]]; then
    if ! cpu_vendor=$(cpu-vendor); then
        printf "unable to get cpu vendor\n" >&2
        return 1
    fi
    export BOOTSTRAP_CPU_VENDOR=$cpu_vendor
fi

if [[ ! -v BOOTSTRAP_GPU_MODULES ]]; then
    if ! gpu_modules=$(gpu-modules | paste -sd' '); then
        printf "unable to get gpu kernel modules\n" >&2
        return 1
    fi
    export BOOTSTRAP_GPU_MODULES=$gpu_modules
fi

if [[ ! -v BOOTSTRAP_BOOT_FIRMWARE ]]; then
    if [[ -d /sys/firmware/efi/efivars ]]; then
        export BOOTSTRAP_BOOT_FIRMWARE=uefi
    else
        export BOOTSTRAP_BOOT_FIRMWARE=bios
    fi
fi

export BOOTSTRAP_PART_BOOT_NAME=${BOOTSTRAP_PART_BOOT_NAME:-boot}

case $BOOTSTRAP_BOOT_FIRMWARE in
uefi)
    export BOOTSTRAP_PART_BOOT_TYPE=C12A7328-F81F-11D2-BA4B-00A0C93EC93B
    export BOOTSTRAP_PART_BOOT_SIZE=${BOOTSTRAP_PART_BOOT_SIZE:-100M}
    export BOOTSTRAP_UEFI_MOUNT=${BOOTSTRAP_UEFI_MOUNT:-/efi}
    ;;
bios)
    export BOOTSTRAP_PART_BOOT_TYPE=21686148-6449-6E6F-744E-656564454649
    export BOOTSTRAP_PART_BOOT_SIZE=${BOOTSTRAP_PART_BOOT_SIZE:-1M}
    ;;
esac

export BOOTSTRAP_PART_SYS_NAME=${BOOTSTRAP_PART_SYS_NAME:-sys}
export BOOTSTRAP_PART_SYS_TYPE=${BOOTSTRAP_PART_SYS_TYPE:-0FC63DAF-8483-4772-8E79-3D69D8477DE4}
export BOOTSTRAP_PART_SYS_SIZE=${BOOTSTRAP_PART_SYS_SIZE:-+}

if [[ ! -v BOOTSTRAP_USE_TRIM ]] && device-is-ssd "$BOOTSTRAP_DEVICE"; then
    export BOOTSTRAP_USE_TRIM=1
fi

if [[ ! -v BOOTSTRAP_USE_WIRELESS ]] && network-interfaces | grep -q '^wl'; then
    export BOOTSTRAP_USE_WIRELESS=1
fi

export BOOTSTRAP_HOSTNAME=${BOOTSTRAP_HOSTNAME:-arch}
export BOOTSTRAP_LANG=${BOOTSTRAP_LANG:-en_US.UTF-8}
export BOOTSTRAP_KEYMAP=${BOOTSTRAP_KEYMAP:-us}

if [[ ! -v BOOTSTRAP_TIMEZONE ]]; then
    if ! timezone=$(timezone); then
        printf "unable to get time zone\n" >&2
        return 1
    fi
    export BOOTSTRAP_TIMEZONE=$timezone
fi

export BOOTSTRAP_MIRROR_COUNTRY=${BOOTSTRAP_MIRROR_COUNTRY:-US}

export BOOTSTRAP_ADMIN_LOGIN=${BOOTSTRAP_ADMIN_LOGIN:-admin}
export BOOTSTRAP_ADMIN_GROUP=${BOOTSTRAP_ADMIN_GROUP:-wheel}
export BOOTSTRAP_ADMIN_PASSWORD=${BOOTSTRAP_ADMIN_PASSWORD:-hunter2}

unset BOOTSTRAP_ADMIN_SHELL_PACKAGE
if [[ -v BOOTSTRAP_ADMIN_SHELL ]]; then
    shell=${BOOTSTRAP_ADMIN_SHELL##*/}
    if ! grep -qxF "$shell" "$BOOTSTRAP_CONFIG"/packages/shell; then
        printf "%s: invalid shell: %s\n" "$0" "$shell" >&2
        return 2
    fi
    BOOTSTRAP_ADMIN_SHELL_PACKAGE=$shell
fi
export BOOTSTRAP_ADMIN_SHELL_PACKAGE

kernel=linux${BOOTSTRAP_KERNEL:+-$BOOTSTRAP_KERNEL}
if ! grep -qxF "$kernel" "$BOOTSTRAP_CONFIG"/packages/kernel; then
    printf "%s: invalid kernel: %s\n" "$0" "$kernel" >&2
    return 2
fi
export BOOTSTRAP_KERNEL_PACKAGE=$kernel

export BOOTSTRAP_KERNEL_LOGLEVEL=${BOOTSTRAP_KERNEL_LOGLEVEL:-4}
export BOOTSTRAP_KERNEL_CONSOLEBLANK=${BOOTSTRAP_KERNEL_CONSOLEBLANK:-0}
