#!/usr/bin/env bash

export CONFIG_DIR=${1:-$PWD/config}

. "$CONFIG_DIR"/environment || return 1

: "${INSTALL_DEVICE:?}"

export PATH=$PWD/bin:$PATH

export INSTALL_DIR=${INSTALL_DIR:-/mnt/install}

export INSTALL_BOOT_DEVICE=${INSTALL_DEVICE}1
export INSTALL_OS_DEVICE=${INSTALL_DEVICE}2

if [[ -v INSTALL_LUKS_PASSPHRASE ]]; then
    export INSTALL_DEVICE_IS_LUKS=1
    export INSTALL_LUKS_DEVICE=$INSTALL_OS_DEVICE
    export INSTALL_LUKS_MAPPER_NAME=${INSTALL_LUKS_MAPPER_NAME:-os}
    export INSTALL_LUKS_MAPPER=/dev/mapper/$INSTALL_LUKS_MAPPER_NAME
    export INSTALL_LUKS_KEYFILE=${INSTALL_LUKS_KEYFILE:-/crypto_keyfile.bin}
    export INSTALL_LVM_DEVICE=$INSTALL_LUKS_MAPPER
else
    export INSTALL_DEVICE_IS_LUKS=0
    export INSTALL_LVM_DEVICE=$INSTALL_OS_DEVICE
fi

export INSTALL_ROOT_NAME=${INSTALL_ROOT_NAME:-root}
export INSTALL_SWAP_NAME=${INSTALL_SWAP_NAME:-swap}

export INSTALL_LVM_VG_NAME=${INSTALL_LVM_VG_NAME:-vg}
export INSTALL_LVM_LV_ROOT_NAME=${INSTALL_LVM_LV_ROOT_NAME:-$INSTALL_ROOT_NAME}
export INSTALL_LVM_LV_SWAP_NAME=${INSTALL_LVM_LV_SWAP_NAME:-$INSTALL_SWAP_NAME}

export INSTALL_ROOT_DEVICE=/dev/mapper/$INSTALL_LVM_VG_NAME-$INSTALL_LVM_LV_ROOT_NAME
export INSTALL_SWAP_DEVICE=/dev/mapper/$INSTALL_LVM_VG_NAME-$INSTALL_LVM_LV_SWAP_NAME

export INSTALL_FS_ROOT_LABEL=${INSTALL_FS_ROOT_LABEL:-$INSTALL_ROOT_NAME}
export INSTALL_FS_SWAP_LABEL=${INSTALL_FS_SWAP_LABEL:-$INSTALL_SWAP_NAME}

export INSTALL_FS_MOUNT_OPTIONS=${INSTALL_FS_MOUNT_OPTIONS:-autodefrag,compress=zstd}

if [[ ! -v INSTALL_CPU_VENDOR ]]; then
    case $(grep -w -m1 '^vendor_id' /proc/cpuinfo | awk '{print $NF}') in
    GenuineIntel) export INSTALL_CPU_VENDOR=intel ;;
    AuthenticAMD) export INSTALL_CPU_VENDOR=amd ;;
    esac
fi

if [[ ! -v INSTALL_BOOT_TYPE ]]; then
    if [[ -d /sys/firmware/efi/efivars ]]; then
        export INSTALL_BOOT_TYPE=uefi
    else
        export INSTALL_BOOT_TYPE=bios
    fi
fi

case $INSTALL_BOOT_TYPE in
uefi)
    export INSTALL_BOOT_PARTITION_FLAG=esp
    export INSTALL_BOOT_PARTITION_SIZE=${INSTALL_BOOT_PARTITION_SIZE:-512}
    export INSTALL_BOOT_UEFI_DIR=${INSTALL_BOOT_UEFI_DIR:-/boot/efi}
    ;;
bios)
    export INSTALL_BOOT_PARTITION_FLAG=bios_grub
    export INSTALL_BOOT_PARTITION_SIZE=${INSTALL_BOOT_PARTITION_SIZE:-2}
    ;;
esac

if [[ ! -v INSTALL_DEVICE_IS_SSD ]]; then
    if (($(</sys/block/"${INSTALL_DEVICE##*/}"/queue/rotational))); then
        export INSTALL_DEVICE_IS_SSD=0
    else
        export INSTALL_DEVICE_IS_SSD=1
    fi
fi

if [[ ! -v INSTALL_SWAP_SIZE ]]; then
    # The swap size should be at least as big as physical memory.
    INSTALL_SWAP_SIZE=$(guess-mem-total) || return 1
    export INSTALL_SWAP_SIZE
fi

if [[ ! -v INSTALL_NET_HAS_WIRELESS ]]; then
    if find /sys/class/net -mindepth 1 | grep -q "^wl"; then
        export INSTALL_NET_HAS_WIRELESS=1
    else
        export INSTALL_NET_HAS_WIRELESS=0
    fi
fi

export INSTALL_HOSTNAME=${INSTALL_HOSTNAME:-arch}

if [[ ! -v INSTALL_LANG ]]; then
    [[ ! -v LANG && -r /etc/locale.conf ]] && . /etc/locale.conf
    export INSTALL_LANG=${LANG:-en_US.UTF-8}
fi

if [[ ! -v INSTALL_KEYMAP ]]; then
    [[ ! -v KEYMAP && -r /etc/vconsole.conf ]] && . /etc/vconsole.conf
    export INSTALL_KEYMAP=${KEYMAP:-us}
fi

if [[ ! -v INSTALL_FONT ]]; then
    [[ ! -v FONT && -r /etc/vconsole.conf ]] && . /etc/vconsole.conf
    export INSTALL_FONT=${FONT:-Lat2-Terminus16}
fi

if [[ ! -v INSTALL_TIMEZONE ]]; then
    if [[ -r /etc/localtime ]]; then
        INSTALL_TIMEZONE=$(realpath /etc/localtime)
        INSTALL_TIMEZONE=${INSTALL_TIMEZONE#/usr/share/zoneinfo/}
    else
        INSTALL_TIMEZONE=UTC
    fi
    export INSTALL_TIMEZONE
fi

if [[ ! -v INSTALL_COUNTRY ]]; then
    INSTALL_COUNTRY=${INSTALL_LANG%.*}
    INSTALL_COUNTRY=${INSTALL_COUNTRY#*_}
    export INSTALL_COUNTRY
fi

export INSTALL_SUDOER_GROUP=${INSTALL_SUDOER_GROUP:-wheel}
export INSTALL_SUDOER_USERNAME=${INSTALL_SUDOER_USERNAME:-admin}
export INSTALL_SUDOER_PASSWORD=${INSTALL_SUDOER_PASSWORD:-hunter2}

# Show the current environment as a sanity check.
set | grep '^INSTALL_' | sort
