#!/usr/bin/env bash

set -euo pipefail

systemctl stop reflector.service

if [[ ! -v BOOTSTRAP_PACKAGE_REPO_DIR ]]; then
    reflector --verbose --save /etc/pacman.d/mirrorlist --protocol https --country US --latest 20 --sort rate
fi

pacman -Syy
