#!/usr/bin/env bash

set -euo pipefail

self_name=${0##*/}

usage="Test installation in a virtual machine.

Usage:
    $self_name -h|--help
    $self_name [OPTIONS] ISO_FILE

Options:
    -e    edit configuration before building cloud-init image

    -y    proceed with the installation
          (specify twice to also reboot into the new system)

Arguments:
    ISO_FILE     installation media ISO file
"

if (($# > 0)); then
    if [[ $1 == -h || $1 == --help ]]; then
        printf "%s\n" "$usage"
        exit
    fi
fi

mkvm_opts=()

while getopts "ey" opt; do
    case $opt in
    e | y) mkvm_opts+=(-"$opt") ;;
    *) exit 2 ;;
    esac
done
shift $((OPTIND - 1))

media_file=${1:?missing media file}

temp_dir=$(mktemp -d -t "$self_name-$$".XXXXXXXXXX)
trap 'rm -rf "$temp_dir"' EXIT

disk_file=$temp_dir/disk.cow

./scripts/mkvm "${mkvm_opts[@]}" "$media_file" "$disk_file"

./scripts/vm "$disk_file"
