#!/usr/bin/env bash

set -eu

# Pretend doas is sudo.
ln -sfv /usr/bin/{doas,sudo}

echo "LANG=$INSTALL_LANG" >/etc/locale.conf
sed -i -e "/#$INSTALL_LANG/s/^#//" /etc/locale.gen
locale-gen

cat >/etc/vconsole.conf <<-EOF
FONT=$INSTALL_FONT
KEYMAP=$INSTALL_KEYMAP
EOF

echo "$INSTALL_HOSTNAME" >/etc/hostname

ln -sf "/usr/share/zoneinfo/$INSTALL_TIMEZONE" /etc/localtime
hwclock --systohc --utc

echo "permit ${INSTALL_DOAS_NOPASS:+nopass }:wheel" >/etc/doas.conf

useradd \
    --create-home --groups users,wheel \
    ${INSTALL_DOAS_SHELL:+--shell "$INSTALL_DOAS_SHELL"} \
    "$INSTALL_DOAS_USERNAME"

chpasswd <<<"$INSTALL_DOAS_USERNAME:$INSTALL_DOAS_PASSWORD"

passwd --delete root

systemctl enable systemd-{networkd,resolved,timesyncd}.service

systemctl enable {sshd,iwd}.service

systemctl enable reflector.{service,timer}

systemctl enable fstrim.timer

if [[ $INSTALL_VM_TYPE == oracle ]]; then
    systemctl enable vboxservice.service
    gpasswd --add "$INSTALL_DOAS_USERNAME" vboxsf
fi
