unset partition_prefix

if [[ ${BOOTSTRAP_INSTALL_DEVICE##*/} == nvme* ]]; then
    partition_prefix=p
fi

export BOOTSTRAP_BOOT_DEVICE=${BOOTSTRAP_BOOT_DEVICE:-${BOOTSTRAP_INSTALL_DEVICE}${partition_prefix:-}1}
export BOOTSTRAP_SYS_DEVICE=${BOOTSTRAP_SYS_DEVICE:-${BOOTSTRAP_INSTALL_DEVICE}${partition_prefix:-}2}

export BOOTSTRAP_PART_BOOT_NAME=${BOOTSTRAP_PART_BOOT_NAME:-boot}

case $BOOTSTRAP_BOOT_FIRMWARE in
uefi)
    export BOOTSTRAP_PART_BOOT_TYPE=C12A7328-F81F-11D2-BA4B-00A0C93EC93B
    export BOOTSTRAP_PART_BOOT_SIZE=${BOOTSTRAP_PART_BOOT_SIZE:-100M}
    export BOOTSTRAP_UEFI_MOUNT_DIR=${BOOTSTRAP_UEFI_MOUNT_DIR:-/efi}
    ;;
bios)
    export BOOTSTRAP_PART_BOOT_TYPE=21686148-6449-6E6F-744E-656564454649
    export BOOTSTRAP_PART_BOOT_SIZE=${BOOTSTRAP_PART_BOOT_SIZE:-1M}
    ;;
esac

export BOOTSTRAP_PART_SYS_NAME=${BOOTSTRAP_PART_SYS_NAME:-sys}
export BOOTSTRAP_PART_SYS_TYPE=${BOOTSTRAP_PART_SYS_TYPE:-0FC63DAF-8483-4772-8E79-3D69D8477DE4}
export BOOTSTRAP_PART_SYS_SIZE=${BOOTSTRAP_PART_SYS_SIZE:-+}
