export BOOTSTRAP_LVM_DEVICE=$BOOTSTRAP_SYS_DEVICE

export BOOTSTRAP_LVM_VG_NAME=${BOOTSTRAP_LVM_VG_NAME:-sys}

export BOOTSTRAP_LVM_LV_SWAP_NAME=${BOOTSTRAP_LVM_LV_SWAP_NAME:-swap}

if [[ ! -v BOOTSTRAP_LVM_LV_SWAP_SIZE ]]; then
    if [[ -v BOOTSTRAP_MEMORY_SIZE ]]; then
        BOOTSTRAP_LVM_LV_SWAP_SIZE=$BOOTSTRAP_MEMORY_SIZE
    elif memory_size=$(memory-size); then
        BOOTSTRAP_LVM_LV_SWAP_SIZE=$memory_size
    else
        printf "unable to get information about physical memory\n" >&2
        return 1
    fi
    export BOOTSTRAP_LVM_LV_SWAP_SIZE
fi

export BOOTSTRAP_LVM_LV_ROOT_NAME=${BOOTSTRAP_LVM_LV_ROOT_NAME:-root}
export BOOTSTRAP_LVM_LV_ROOT_EXTENTS=${BOOTSTRAP_LVM_LV_ROOT_EXTENTS:-+100%FREE}

export BOOTSTRAP_SWAP_DEVICE=/dev/mapper/$BOOTSTRAP_LVM_VG_NAME-$BOOTSTRAP_LVM_LV_SWAP_NAME
export BOOTSTRAP_ROOT_DEVICE=/dev/mapper/$BOOTSTRAP_LVM_VG_NAME-$BOOTSTRAP_LVM_LV_ROOT_NAME
