[[ -v BOOTSTRAP_USE_LUKS ]] || return 0

export BOOTSTRAP_LUKS_DEVICE=$BOOTSTRAP_SYS_DEVICE

export BOOTSTRAP_LUKS_MAPPER_NAME=${BOOTSTRAP_LUKS_MAPPER_NAME:-sys}
export BOOTSTRAP_LUKS_MAPPER_DEVICE=/dev/mapper/$BOOTSTRAP_LUKS_MAPPER_NAME

export BOOTSTRAP_LUKS_KEYFILE_PATH=${BOOTSTRAP_LUKS_KEYFILE_PATH:-/crypto_keyfile.bin}
export BOOTSTRAP_LUKS_PASSPHRASE=${BOOTSTRAP_LUKS_PASSPHRASE:-hunter2}

export BOOTSTRAP_LVM_DEVICE=$BOOTSTRAP_LUKS_MAPPER_DEVICE
